#ifndef MCP2515_REGS_H_
#define MCP2515_REGS_H_

/******************************************************************************
 * Регистры
 *****************************************************************************/

#define CANSTAT 14U
#define CANCTRL 15U

#define RXF0SIDH  0x00U
#define RXF0SIDL  0x01U
#define RXF0EID8  0x02U
#define RXF0EID0  0x03U
#define RXF1SIDH  0x04U
#define RXF1SIDL  0x05U
#define RXF1EID8  0x06U
#define RXF1EID0  0x07U
#define RXF2SIDH  0x08U
#define RXF2SIDL  0x09U
#define RXF2EID8  0x0AU
#define RXF2EID0  0x0BU
#define BFPCTRL   0x0CU
#define TXRTSCTRL 0x0DU

#define RXF3SIDH  0x10U
#define RXF3SIDL  0x11U
#define RXF3EID8  0x12U
#define RXF3EID0  0x13U
#define RXF4SIDH  0x14U
#define RXF4SIDL  0x15U
#define RXF4EID8  0x16U
#define RXF4EID0  0x17U
#define RXF5SIDH  0x18U
#define RXF5SIDL  0x19U
#define RXF5EID8  0x1AU
#define RXF5EID0  0x1BU
#define TEC       0x1CU
#define REC       0x1DU

#define RXM0SIDH  0x20U
#define RXM0SIDL  0x21U
#define RXM0EID8  0x22U
#define RXM0EID0  0x23U
#define RXM1SIDH  0x24U
#define RXM1SIDL  0x25U
#define RXM1EID8  0x26U
#define RXM1EID0  0x27U
#define CNF3      0x28U
#define CNF2      0x29U
#define CNF1      0x2AU
#define CANINTE   0x2BU
#define CANINTF   0x2CU
#define EFLG      0x2DU

#define TXB0CTRL  0x30U
#define TXB0SIDH  0x31U
#define TXB0SIDL  0x32U
#define TXB0EID8  0x33U
#define TXB0EID0  0x34U
#define TXB0DLC   0x35U
#define TXB0D0    0x36U
#define TXB0D1    0x37U
#define TXB0D2    0x38U
#define TXB0D3    0x39U
#define TXB0D4    0x3AU
#define TXB0D5    0x3BU
#define TXB0D6    0x3CU
#define TXB0D7    0x3DU

#define TXB1CTRL  0x40U
#define TXB1SIDH  0x41U
#define TXB1SIDL  0x42U
#define TXB1EID8  0x43U
#define TXB1EID0  0x44U
#define TXB1DLC   0x45U
#define TXB1D0    0x46U
#define TXB1D1    0x47U
#define TXB1D2    0x48U
#define TXB1D3    0x49U
#define TXB1D4    0x4AU
#define TXB1D5    0x4BU
#define TXB1D6    0x4CU
#define TXB1D7    0x4DU

#define TXB2CTRL  0x50U
#define TXB2SIDH  0x51U
#define TXB2SIDL  0x52U
#define TXB2EID8  0x53U
#define TXB2EID0  0x54U
#define TXB2DLC   0x55U
#define TXB2D0    0x56U
#define TXB2D1    0x57U
#define TXB2D2    0x58U
#define TXB2D3    0x59U
#define TXB2D4    0x5AU
#define TXB2D5    0x5BU
#define TXB2D6    0x5CU
#define TXB2D7    0x5DU

#define RXB0CTRL  0x60U
#define RXB0SIDH  0x61U
#define RXB0SIDL  0x62U
#define RXB0EID8  0x63U
#define RXB0EID0  0x64U
#define RXB0DLC   0x65U
#define RXB0D0    0x66U
#define RXB0D1    0x67U
#define RXB0D2    0x68U
#define RXB0D3    0x69U
#define RXB0D4    0x6AU
#define RXB0D5    0x6BU
#define RXB0D6    0x6CU
#define RXB0D7    0x6DU

#define RXB1CTRL  0x70U
#define RXB1SIDH  0x71U
#define RXB1SIDL  0x72U
#define RXB1EID8  0x73U
#define RXB1EID0  0x74U
#define RXB1DLC   0x75U
#define RXB1D0    0x76U
#define RXB1D1    0x77U
#define RXB1D2    0x78U
#define RXB1D3    0x79U
#define RXB1D4    0x7AU
#define RXB1D5    0x7BU
#define RXB1D6    0x7CU
#define RXB1D7    0x7DU

/******************************************************************************
 * Поля регистров
 *****************************************************************************/

// CANSTAT

#define CANSTAT_OPMOD_POS     5U
#define CANSTAT_OPMOD_MASK   (7U << CANSTAT_OPMOD_POS)
#define CANSTAT_OPMOD_NORMAL (0U << CANSTAT_OPMOD_POS)
#define CANSTAT_OPMOD_SLEEP  (1U << CANSTAT_OPMOD_POS)
#define CANSTAT_OPMOD_LOOP   (2U << CANSTAT_OPMOD_POS)
#define CANSTAT_OPMOD_LISTEN (3U << CANSTAT_OPMOD_POS)
#define CANSTAT_OPMOD_CONFIG (4U << CANSTAT_OPMOD_POS)

#define CANSTAT_ICOD_POS      1U
#define CANSTAT_ICOD_MASK    (7U << CANSTAT_ICOD_POS)
#define CANSTAT_ICOD_NO      (0U << CANSTAT_ICOD_POS)
#define CANSTAT_ICOD_ERROR   (1U << CANSTAT_ICOD_POS)
#define CANSTAT_ICOD_WAKEUP  (2U << CANSTAT_ICOD_POS)
#define CANSTAT_ICOD_TXB0    (3U << CANSTAT_ICOD_POS)
#define CANSTAT_ICOD_TXB1    (4U << CANSTAT_ICOD_POS)
#define CANSTAT_ICOD_TXB2    (5U << CANSTAT_ICOD_POS)
#define CANSTAT_ICOD_RXB0    (6U << CANSTAT_ICOD_POS)
#define CANSTAT_ICOD_RXB1    (7U << CANSTAT_ICOD_POS)

// CANCTRL

#define CANCTRL_REQOP_POS     5U
#define CANCTRL_REQOP_MASK   (7U << CANCTRL_REQOP_POS)
#define CANCTRL_REQOP_NORMAL (0U << CANCTRL_REQOP_POS)
#define CANCTRL_REQOP_SLEEP  (1U << CANCTRL_REQOP_POS)
#define CANCTRL_REQOP_LOOP   (2U << CANCTRL_REQOP_POS)
#define CANCTRL_REQOP_LISTEN (3U << CANCTRL_REQOP_POS)
#define CANCTRL_REQOP_CONFIG (4U << CANCTRL_REQOP_POS)

#define CANCTRL_ABAT_POS      4U
#define CANCTRL_ABAT_MASK    (1U << CANCTRL_ABAT_POS)
#define CANCTRL_ABAT          CANCTRL_ABAT_MASK

#define CANCTRL_OSM_POS       3U
#define CANCTRL_OSM_MASK     (1U << CANCTRL_OSM_POS)
#define CANCTRL_OSM           CANCTRL_OSM_MASK

#define CANCTRL_CLKEN_POS     2U
#define CANCTRL_CLKEN_MASK   (1U << CANCTRL_CLKEN_POS)
#define CANCTRL_CLKEN         CANCTRL_CLKEN_MASK

#define CANCTRL_CLKPRE_POS    0U
#define CANCTRL_CLKPRE_MASK  (3U << CANCTRL_CLKPRE_POS)
#define CANCTRL_CLKPRE_DIV1  (0U << CANCTRL_CLKPRE_POS)
#define CANCTRL_CLKPRE_DIV2  (1U << CANCTRL_CLKPRE_POS)
#define CANCTRL_CLKPRE_DIV4  (2U << CANCTRL_CLKPRE_POS)
#define CANCTRL_CLKPRE_DIV8  (3U << CANCTRL_CLKPRE_POS)

// BFPCTRL

#define BFPCTRL_B1BFS_POS     5U
#define BFPCTRL_B1BFS_MASK   (1U << BFPCTRL_B1BFS_POS)
#define BFPCTRL_B1BFS         BFPCTRL_B1BFS_MASK

#define BFPCTRL_B0BFS_POS     4U
#define BFPCTRL_B0BFS_MASK   (1U << BFPCTRL_B0BFS_POS)
#define BFPCTRL_B0BFS         BFPCTRL_B0BFS_MASK

#define BFPCTRL_B1BFE_POS     3U
#define BFPCTRL_B1BFE_MASK   (1U << BFPCTRL_B1BFE_POS)
#define BFPCTRL_B1BFE         BFPCTRL_B1BFE_MASK

#define BFPCTRL_B0BFE_POS     2U
#define BFPCTRL_B0BFE_MASK   (1U << BFPCTRL_B0BFE_MASK)
#define BFPCTRL_B0BFE         BFPCTRL_B0BFE_MASK

#define BFPCTRL_B1BFM_POS     1U
#define BFPCTRL_B1BFM_MASK   (1U << BFPCTRL_B1BFM_POS)
#define BFPCTRL_B1BFM         BFPCTRL_B1BFM_MASK

#define BFPCTRL_B0BFM_POS     0U
#define BFPCTRL_B0BFM_MASK   (1U << BFPCTRL_B0BFM_POS)
#define BFPCTRL_B0BFM         BFPCTRL_B0BFM_MASK

// TXRTSCTRL

#define TXRTSCTRL_B2RTS_POS    5U
#define TXRTSCTRL_B2RTS_MASK  (1U << TXRTSCTRL_B2RTS_POS)
#define TXRTSCTRL_B2RTS        TXRTSCTRL_B2RTS_MASK

#define TXRTSCTRL_B1RTS_POS    4U
#define TXRTSCTRL_B1RTS_MASK  (1U << TXRTSCTRL_B1RTS_POS)
#define TXRTSCTRL_B1RTS        TXRTSCTRL_B1RTS_MASK

#define TXRTSCTRL_B0RTS_POS    3U
#define TXRTSCTRL_B0RTS_MASK  (1U << TXRTSCTRL_B0RTS_POS)
#define TXRTSCTRL_B0RTS        TXRTSCTRL_B0RTS_MASK

#define TXRTSCTRL_B2RTSM_POS   2U
#define TXRTSCTRL_B2RTSM_MASK (1U << TXRTSCTRL_B2RTSM_POS)
#define TXRTSCTRL_B2RTSM       TXRTSCTRL_B2RTSM_MASK

#define TXRTSCTRL_B1RTSM_POS   1U
#define TXRTSCTRL_B1RTSM_MASK (1U << TXRTSCTRL_B1RTSM_POS)
#define TXRTSCTRL_B1RTSM       TXRTSCTRL_B1RTSM_MASK

#define TXRTSCTRL_B0RTSM_POS   0U
#define TXRTSCTRL_B0RTSM_MASK (1U << TXRTSCTRL_B0RTSM_POS)
#define TXRTSCTRL_B0RTSM       TXRTSCTRL_B0RTSM_MASK

// CNF3

#define CNF3_SOF_POS          7U
#define CNF3_SOF_MASK        (1U << CNF3_SOF_POS)
#define CNF3_SOF              CNF3_SOF_MASK

#define CNF3_WAKFIL_POS       6U
#define CNF3_WAKFIL_MASK     (1U << CNF3_WAKFIL_POS)
#define CNF3_WAKFIL           CNF3_WAKFIL_MASK

#define CNF3_PHSEG2_POS       0U
#define CNF3_PHSEG2_MASK     (7U << CNF3_PHSEG2_POS)

// CNF2

#define CNF2_BTLMODE_POS      7U
#define CNF2_BTLMODE_MASK    (1U << CNF2_BTLMODE_POS)
#define CNF2_BTLMODE          CNF2_BTLMODE_MASK

#define CNF2_SAM_POS          6U
#define CNF2_SAM_MASK        (1U << CNF2_SAM_POS)
#define CNF2_SAM              CNF2_SAM_MASK

#define CNF2_PHSEG1_POS       3U
#define CNF2_PHSEG1_MASK     (7U << CNF2_PHSEG1_POS)

#define CNF2_PRSEG_POS        0U
#define CNF2_PRSEG_MASK      (7U << CNF2_PRSEG_POS)

// CNF1

#define CNF1_SJW_POS          6U
#define CNF1_SJW_MASK        (3U << CNF1_SJW_POS)
#define CNF1_SJW_1TQ         (0U << CNF1_SJW_POS)
#define CNF1_SJW_2TQ         (1U << CNF1_SJW_POS)
#define CNF1_SJW_3TQ         (2U << CNF1_SJW_POS)
#define CNF1_SJW_4TQ         (3U << CNF1_SJW_POS)

#define CNF1_BRP_POS          0U
#define CNF1_BRP_MASK        (0x3FU << CNF1_BRP_POS)

// CANINTE

#define CANINTE_MERRE_POS     7U
#define CANINTE_MERRE_MASK   (1U << CANINTE_MERRE_POS)
#define CANINTE_MERRE         CANINTE_MERRE_MASK

#define CANINTE_WAKIE_POS     6U
#define CANINTE_WAKIE_MASK   (1U << CANINTE_WAKIE_POS)
#define CANINTE_WAKIE         CANINTE_WAKIE_MASK

#define CANINTE_ERRIE_POS     5U
#define CANINTE_ERRIE_MASK   (1U << CANINTE_ERRIE_POS)
#define CANINTE_ERRIE         CANINTE_ERRIE_MASK

#define CANINTE_TX2IE_POS     4U
#define CANINTE_TX2IE_MASK   (1U << CANINTE_TX2IE_POS)
#define CANINTE_TX2IE         CANINTE_TX2IE_MASK

#define CANINTE_TX1IE_POS     3U
#define CANINTE_TX1IE_MASK   (1U << CANINTE_TX1IE_POS)
#define CANINTE_TX1IE         CANINTE_TX1IE_MASK

#define CANINTE_TX0IE_POS     2U
#define CANINTE_TX0IE_MASK   (1U << CANINTE_TX0IE_POS)
#define CANINTE_TX0IE         CANINTE_TX0IE_MASK

#define CANINTE_RX1IE_POS     1U
#define CANINTE_RX1IE_MASK   (1U << CANINTE_RX1IE_POS)
#define CANINTE_RX1IE         CANINTE_RX1IE_MASK

#define CANINTE_RX0IE_POS     0U
#define CANINTE_RX0IE_MASK   (1U << CANINTE_RX0IE_POS)
#define CANINTE_RX0IE         CANINTE_RX0IE_MASK

// CNAINTF

#define CANINTF_MERRF_POS     7U
#define CANINTF_MERRF_MASK   (1U << CANINTF_MERRF_POS)
#define CANINTF_MERRF         CANINTF_MERRF_MASK

#define CANINTF_WAKIF_POS     6U
#define CANINTF_WAKIF_MASK   (1U << CANINTF_WAKIF_POS)
#define CANINTF_WAKIF         CANINTF_WAKIF_MASK

#define CANINTF_ERRIF_POS     5U
#define CANINTF_ERRIF_MASK   (1U << CANINTF_ERRIF_POS)
#define CANINTF_ERRIF         CANINTF_ERRIF_MASK

#define CANINTF_TX2IF_POS     4U
#define CANINTF_TX2IF_MASK   (1U << CANINTF_TX2IF_POS)
#define CANINTF_TX2IF         CANINTF_TX2IF_MASK

#define CANINTF_TX1IF_POS     3U
#define CANINTF_TX1IF_MASK   (1U << CANINTF_TX1IF_POS)
#define CANINTF_TX1IF         CANINTF_TX1IF_MASK

#define CANINTF_TX0IF_POS     2U
#define CANINTF_TX0IF_MASK   (1U << CANINTF_TX0IF_POS)
#define CANINTF_TX0IF         CANINTF_TX0IF_MASK

#define CANINTF_RX1IF_POS     1U
#define CANINTF_RX1IF_MASK   (1U << CANINTF_RX1IF_POS)
#define CANINTF_RX1IF         CANINTF_RX1IF_MASK

#define CANINTF_RX0IF_POS     0U
#define CANINTF_RX0IF_MASK   (1U << CANINTF_RX0IF_POS)
#define CANINTF_RX0IF         CANINTF_RX0IF_MASK

// EFLG

#define EFLG_RX1OVR_POS       7U
#define EFLG_RX1OVR_MASK     (1U << EFLG_RX1OVR_POS)
#define EFLG_RX1OVR           EFLG_RX1OVR_MASK

#define EFLG_RX0OVR_POS       6U
#define EFLG_RX0OVR_MASK     (1U << EFLG_RX0OVR_POS)
#define EFLG_RX0OVR           EFLG_RX0OVR_MASK

#define EFLG_TXBO_POS         5U
#define EFLG_TXBO_MASK       (1U << EFLG_TXBO_POS)
#define EFLG_TXBO             EFLG_TXBO_MASK

#define EFLG_TXEP_POS         4U
#define EFLG_TXEP_MASK       (1U << EFLG_TXEP_POS)
#define EFLG_TXEP             EFLG_TXEP_MASK

#define EFLG_RXEP_POS         3U
#define EFLG_RXEP_MASK       (1U << EFLG_RXEP_POS)
#define EFLG_RXEP             EFLG_RXEP_MASK

#define EFLG_TXWAR_POS        2U
#define EFLG_TXWAR_MASK      (1U << EFLG_TXWAR_POS)
#define EFLG_TXWAR            EFLG_TXWAR_MASK

#define EFLG_RXWAR_POS        1U
#define EFLG_RXWAR_MASK      (1U << EFLG_RXWAR_POS)
#define EFLG_RXWAR            EFLG_RXWAR_MASK

#define EFLG_EWARN_POS        0U
#define EFLG_EWARN_MASK      (1U << EFLG_EWARN_POS)
#define EFLG_EWARN            EFLG_EWARN_MASK

// TXBnCTRL

#define TXBnCTRL_ABTF_POS     6U
#define TXBnCTRL_ABTF_MASK   (1U << TXBnCTRL_ABTF_POS)
#define TXBnCTRL_ABTF         TXBnCTRL_ABTF_MASK

#define TXBnCTRL_MLOA_POS     5U
#define TXBnCTRL_MLOA_MASK   (1U << TXBnCTRL_MLOA_POS)
#define TXBnCTRL_MLOA         TXBnCTRL_MLOA_MASK

#define TXBnCTRL_TXERR_POS    4U
#define TXBnCTRL_TXERR_MASK  (1U << TXBnCTRL_TXERR_POS)
#define TXBnCTRL_TXERR        TXBnCTRL_TXERR_MASK

#define TXBnCTRL_TXREQ_POS    3U
#define TXBnCTRL_TXREQ_MASK  (1U << TXBnCTRL_TXREQ_POS)
#define TXBnCTRL_TXREQ        TXBnCTRL_TXREQ_MASK

#define TXBnCTRL_TXP_POS      0U
#define TXBnCTRL_TXP_MASK    (3U << TXBnCTRL_TXP_POS)
#define TXBnCTRL_TXP_HIGEST  (3U << TXBnCTRL_TXP_POS)
#define TXBnCTRL_TXP_HIGH    (2U << TXBnCTRL_TXP_POS)
#define TXBnCTRL_TXP_LOW     (1U << TXBnCTRL_TXP_POS)
#define TXBnCTRL_TXP_LOWEST  (0U << TXBnCTRL_TXP_POS)

// RXB0CTRL

#define RXB0CTRL_RXM_POS       5U
#define RXB0CTRL_RXM_MASK     (3U << RXB0CTRL_RXM_POS)
#define RXB0CTRL_RXM_OFF      (3U << RXB0CTRL_RXM_POS)
#define RXB0CTRL_RXM_VALIDEXT (2U << RXB0CTRL_RXM_POS)
#define RXB0CTRL_RXM_VALIDSTD (1U << RXB0CTRL_RXM_POS)
#define RXB0CTRL_RXM_ALL      (0U << RXB0CTRL_RXM_POS)

#define RXB0CTRL_RXRTR_POS    3U
#define RXB0CTRL_RXRTR_MASK  (1U << RXB0CTRL_RXRTR_POS)
#define RXB0CTRL_RXRTR        RXB0CTRL_RXRTR_MASK

#define RXB0CTRL_BUKT_POS     2U
#define RXB0CTRL_BUKT_MASK   (1U << RXB0CTRL_BUKT_POS)
#define RXB0CTRL_BUKT         RXB0CTRL_BUKT_MASK

#define RXB0CTRL_BUKT1_POS    1U
#define RXB0CTRL_BUKT1_MASK  (1U << RXB0CTRL_BUKT1_POS)
#define RXB0CTRL_BUKT1        RXB0CTRL_BUKT1_MASK

#define RXB0CTRL_FILHIT_POS   0U
#define RXB0CTRL_FILHIT_MASK (1U << RXB0CTRL_FILHIT_POS)
#define RXB0CTRL_FILHIT       RXB0CTRL_FILHIT_MASK

// RXB1CTRL

#define RXB1CTRL_RXM_POS       5U
#define RXB1CTRL_RXM_MASK     (3U << RXB1CTRL_RXM_POS)
#define RXB1CTRL_RXM_OFF      (3U << RXB1CTRL_RXM_POS)
#define RXB1CTRL_RXM_VALIDEXT (2U << RXB1CTRL_RXM_POS)
#define RXB1CTRL_RXM_VALIDSTD (1U << RXB1CTRL_RXM_POS)
#define RXB1CTRL_RXM_ALL      (0U << RXB1CTRL_RXM_POS)

#define RXB1CTRL_RXRTR_POS     3U
#define RXB1CTRL_RXRTR_MASK   (1U << RXB1CTRL_RXRTR_POS)
#define RXB1CTRL_RXRTR         RXB1CTRL_RXRTR_MASK

#define RXB1CTRL_FILHIT_POS   0U
#define RXB1CTRL_FILHIT_MASK (7U << RXB1CTRL_FILHIT_POS)
#define RXB1CTRL_FILHIT_5    (5U << RXB1CTRL_FILHIT_POS)
#define RXB1CTRL_FILHIT_4    (4U << RXB1CTRL_FILHIT_POS)
#define RXB1CTRL_FILHIT_3    (3U << RXB1CTRL_FILHIT_POS)
#define RXB1CTRL_FILHIT_2    (2U << RXB1CTRL_FILHIT_POS)
#define RXB1CTRL_FILHIT_1    (1U << RXB1CTRL_FILHIT_POS)
#define RXB1CTRL_FILHIT_0    (0U << RXB1CTRL_FILHIT_POS)

#endif /* MCP2515_REGS_H_ */
